# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175941ea2de5ab7c29fa8fa223b43f7c89f10f3cf2bd63bd2f68013222f9aecdff4a8f435d70b1e6fcadc885a3357d51c8ad349a636bde811dbd15d4380b9006

test:
  secret_key_base: aa90ab68543aab7307ab5cc17e141e291301367fac482582484666933b2fa76d27a26ac6282c0aac8908d88bed2922ae4a85fb7800114085c133afe741f1407e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
